import re

with open('budget.html', 'r', encoding='utf-8') as f:
    budget_content = f.read()

with open('index.html', 'r', encoding='utf-8') as f:
    index_content = f.read()

# 1. Add budget.css to head
if 'budget.css' not in index_content:
    index_content = index_content.replace(
        '<link rel="stylesheet" href="style.css" />',
        '<link rel="stylesheet" href="style.css" />\n  <link rel="stylesheet" href="budget.css" />'
    )

# 2. Extract SCREEN 3 - LEDGER DETAIL from budget.html
ledger_screen_match = re.search(r'<!-- ═══════════════════════════════════════════════ -->\s*<!--  SCREEN 3 — LEDGER DETAIL.*?</div>\s*</div>\s*(?=<!-- ═══════════════════════════════════════════════ -->\s*<!--  WIDGET DRAWER)', budget_content, re.DOTALL)
if ledger_screen_match:
    ledger_screen_html = ledger_screen_match.group(0)
    # Insert before WIDGET DRAWER in index.html
    index_content = index_content.replace(
        '<!-- ═══════════════════════════════════════════════ -->\n  <!--  WIDGET DRAWER (Bottom Sheet)',
        ledger_screen_html + '\n  <!-- ═══════════════════════════════════════════════ -->\n  <!--  WIDGET DRAWER (Bottom Sheet)'
    )

# 3. Extract Ledger drawer tab button from budget.html
ledger_tab_match = re.search(r'<button class="drawer-tab( active)?" data-tab="ledger">.*?</button>', budget_content, re.DOTALL)
if ledger_tab_match:
    ledger_tab_html = ledger_tab_match.group(0).replace(' active', '') # remove active class
    if 'data-tab="ledger"' not in index_content:
        # Insert before Memo tab in index.html
        index_content = index_content.replace(
            '<button class="drawer-tab" data-tab="memo">',
            ledger_tab_html + '\n          <button class="drawer-tab" data-tab="memo">'
        )

# 4. Extract Ledger tab content from budget.html
ledger_tab_content_match = re.search(r'<!-- Ledger Tab -->.*?<div class="tab-content hidden" id="tab-ledger">.*?</div>\s*(?=<!-- Memo Tab -->)', budget_content, re.DOTALL)
if ledger_tab_content_match:
    ledger_tab_content_html = ledger_tab_content_match.group(0)
    if 'id="tab-ledger"' not in index_content:
        # Insert before Memo tab content in index.html
        index_content = index_content.replace(
            '<!-- Memo Tab -->',
            ledger_tab_content_html + '\n          <!-- Memo Tab -->'
        )

# 5. Fix Memo Tab in index.html
memo_carousel_html = """<!-- Memo Tab -->
          <div class="tab-content hidden" id="tab-memo">
            <h3>Memo Widgets</h3>
            <p class="tab-desc">Select a size for your text note block</p>
            <div class="size-carousel" id="memo-size-carousel">
              <button class="carousel-nav prev" id="memo-carousel-prev">‹</button>
              <div class="carousel-viewport" id="memo-carousel-viewport">
                <!-- Size cards generated by JS -->
              </div>
              <button class="carousel-nav next" id="memo-carousel-next">›</button>
            </div>
            <div class="carousel-dots" id="memo-carousel-dots"></div>
            <button class="btn-primary btn-choose-size" id="btn-choose-memo">Choose this size</button>
          </div>"""
index_content = re.sub(
    r'<!-- Memo Tab -->\s*<div class="tab-content hidden" id="tab-memo">\s*<h3>Memo Widgets</h3>\s*<p class="tab-placeholder">Text note widgets — coming soon</p>\s*</div>',
    memo_carousel_html,
    index_content,
    flags=re.DOTALL
)

# 6. Add Memo fullscreen overlay DOM
memo_overlay_html = """
  <!-- ═══════════════════════════════════════════════ -->
  <!--  MEMO FULLSCREEN OVERLAY                        -->
  <!-- ═══════════════════════════════════════════════ -->
  <div class="memo-fullscreen-overlay hidden" id="memo-fullscreen-overlay">
    <div class="memo-fullscreen-container">
      <header class="memo-fullscreen-header">
        <button class="btn-icon memo-fullscreen-back" id="memo-fullscreen-back">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="M15 18l-6-6 6-6"/></svg>
        </button>
        <h2 class="memo-fullscreen-title" id="memo-fullscreen-title">Memo</h2>
      </header>
      <div class="memo-fullscreen-body" id="memo-fullscreen-body"></div>
    </div>
  </div>
"""
if 'memo-fullscreen-overlay' not in index_content:
    index_content = index_content.replace(
        '<!-- ═══════════════════════════════════════════════ -->\n  <!--  IMAGE CONFIRM DIALOG',
        memo_overlay_html + '\n  <!-- ═══════════════════════════════════════════════ -->\n  <!--  IMAGE CONFIRM DIALOG'
    )

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(index_content)

print("index.html merged successfully!")
